grid_map_topic: /Filtro/filtro_mapa_pre

grid_map_visualizations:

  - name: elevation_points
    type: point_cloud
    params:
      layer: elevation

  - name: noisy_points
    type: point_cloud
    params:
      layer: elevation_noisy

  - name: filtered_points
    type: point_cloud
    params:
      layer: elevation_filtered

  - name: map_region 
    type: map_region
    params:
      color: 3289650
      line_width: 0.003

  - name: elevation_grid
    type: occupancy_grid
    params:
      layer: traversability
      data_min: 0.08
      data_max: -0.0
      color: 005142217 #15600153 # red

  - name: surface_normals
    type: vectors
    params:
      layer_prefix: normal_vectors_
      position_layer: elevation
      scale: 0.5
      line_width: 0.2
      color: 005142217 #15600153 # red

  - name: elevation_cells
    type: grid_cells
    params:
      layer: traversability
      lower_threshold: 0.0
      upper_threshold: 1.0 #0.15